openapi: 3.0.0

info:
  version: 0.0.1
  title: Hex Architecture
  description: Hex Architecture

servers:
  - url: http://localhost:8080/
    description: API location

tags:
  - name: "payments"


paths:
  /payments/balance/{id}:
    parameters:
      - name: id
        description: id of the wallet
        schema:
          type: integer
        in: path
        required: true
    get:
      summary: Returns balance for a specified id.
      tags:
        - "payments"
      description: This is a description
      operationId: getPaymentsBalanceId
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH

components:

  schemas:
    BalanceDTO:
      description: This is the balance model
      type: object
      properties:
        name:
          type: string
        id:
          type: integer
        balance:
          type: float